# Generated by Django 2.2.2 on 2020-07-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_applicant_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, null=True, verbose_name='Mention Your School Name')),
                ('college', models.CharField(max_length=255, null=True, verbose_name='Mention Your college name')),
                ('tenth_percentage', models.FloatField(blank=True, null=True)),
                ('yop_for_tenth', models.IntegerField(blank=True, null=True)),
                ('twelth_percentage', models.FloatField(blank=True, null=True)),
                ('yop_for_twelfth', models.IntegerField(blank=True, null=True)),
                ('bachelor_degree', models.CharField(max_length=255, null=True, verbose_name='Mention Your Bachelor Degree')),
                ('yop_for_bachelors', models.IntegerField(blank=True, null=True)),
                ('CGPA_For_bachelors', models.FloatField(blank=True, null=True)),
                ('masters_degree', models.CharField(max_length=255, null=True, verbose_name='Mention Your Master Degree if any')),
                ('yop_for_masters', models.IntegerField(blank=True, null=True)),
                ('CGPA_For_masters', models.FloatField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='accounts.UserProfile')),
            ],
        ),
    ]
