# Generated by Django 2.2.2 on 2020-07-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codechef',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hackerrank',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='CGPA_For_bachelors',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='education',
            name='CGPA_For_masters',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='education',
            name='tenth_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='education',
            name='twelth_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
