# Generated by Django 2.2.2 on 2020-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(help_text='Mention Your hobbies', max_length=255, null=True),
        ),
    ]
