# Generated by Django 2.2.2 on 2020-07-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200707_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project1', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project2', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project3', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project4', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project5', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project6', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project7', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project8', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project9', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('project10', models.CharField(max_length=255, null=True, verbose_name='Mention project name and give a small desciption about it')),
                ('projectuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectuser', to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'Projects',
            },
        ),
    ]
