# Generated by Django 2.2.2 on 2020-07-09 18:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='user__profilephoto')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Website', models.URLField(blank=True, null=True)),
                ('set_your_profile', models.CharField(choices=[('0', 'Public'), ('1', 'Private')], default='Public', max_length=20)),
                ('about_yourself', models.CharField(max_length=2000, null=True)),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('company_specialization', models.CharField(choices=[('0', 'Php'), ('1', 'JS'), ('2', 'Designing'), ('3', 'Application development'), ('4', 'Painting'), ('5', 'Arts'), ('6', 'Development'), ('7', 'Modeling'), ('8', 'SEO'), ('9', 'Architecture'), ('10', 'Management'), ('11', 'SMM'), ('12', 'Culinary Arts'), ('13', 'Peruvian Cuisine'), ('14', 'Team Management'), ('15', 'patience'), ('16', 'Commitment'), ('17', 'Team Work'), ('18', 'Flexibility'), ('19', 'Stress Management'), ('20', 'Analytical skills'), ('21', 'trainings'), ('22', 'communication skills'), ('23', 'Food Products'), ('24', 'Education'), ('25', 'cooking')], default='Php', max_length=20)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('Established_Date', models.DateField()),
                ('location', models.CharField(max_length=255, null=True)),
                ('Facebook', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('empuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
    ]
