# Generated by Django 2.2.2 on 2020-07-10 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='Established_Date',
            field=models.DateField(verbose_name='Enter date in yy-mm-dd format'),
        ),
        migrations.CreateModel(
            name='subscriptionpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionid', models.CharField(choices=[('1', '499 per month'), ('2', '700 for two months'), ('3', 'Yearly subscription @3400')], default='499 per month', max_length=20)),
                ('status', models.CharField(choices=[('0', 'expired'), ('1', 'active')], default='expired', max_length=20)),
                ('purchasedate', models.DateField(verbose_name='Enter date in yy-mm-dd format')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer')),
            ],
            options={
                'verbose_name': 'subscriptionpack',
                'verbose_name_plural': 'subscriptionpacks',
            },
        ),
        migrations.CreateModel(
            name='savedresume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer')),
                ('resid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'savedresume',
                'verbose_name_plural': 'savedresumes',
            },
        ),
    ]
