# Generated by Django 2.2.2 on 2020-07-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200710_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='settime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indate', models.DateField(verbose_name='Enter date in yyyy-mm-dd format')),
                ('intime', models.TimeField()),
                ('apliid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicant')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer')),
            ],
        ),
    ]
