# Generated by Django 2.2.2 on 2020-07-13 12:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200711_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobexperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_name1', models.CharField(blank=True, max_length=255, verbose_name='Mention Organization Name')),
                ('your_role1', models.CharField(blank=True, max_length=255, verbose_name='Mention Your Role')),
                ('jobtenure1', models.IntegerField(blank=True, null=True, verbose_name='Mention Job Tenure')),
                ('Organization_name2', models.CharField(blank=True, max_length=255, verbose_name='Mention Organization Name')),
                ('jobtenure2', models.IntegerField(blank=True, null=True, verbose_name='Mention Job Tenure')),
                ('your_role2', models.CharField(blank=True, max_length=255, verbose_name='Mention Your Role')),
                ('Organization_name3', models.CharField(blank=True, max_length=255, verbose_name='Mention Organization Name')),
                ('jobtenure3', models.IntegerField(blank=True, null=True, verbose_name='Mention Job Tenure')),
                ('your_role3', models.CharField(blank=True, max_length=255, verbose_name='Mention Your Role')),
                ('Organization_name4', models.CharField(blank=True, max_length=255, verbose_name='Mention Organization Name')),
                ('jobtenure4', models.IntegerField(blank=True, null=True, verbose_name='Mention Job Tenure')),
                ('your_role4', models.CharField(blank=True, max_length=255, verbose_name='Mention Your Role')),
                ('Organization_name5', models.CharField(blank=True, max_length=255, verbose_name='Mention Organization Name')),
                ('jobtenure5', models.IntegerField(blank=True, null=True, verbose_name='Mention Job Tenure')),
                ('your_role5', models.CharField(blank=True, max_length=255, verbose_name='Mention Your Role')),
                ('Organization_name6', models.CharField(blank=True, max_length=255, verbose_name='Mention Organization Name')),
                ('jobtenure6', models.IntegerField(blank=True, null=True, verbose_name='Mention Job Tenure')),
                ('your_role6', models.CharField(blank=True, max_length=255, verbose_name='Mention Your Role')),
                ('euser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='user__profilephoto')),
                ('name', models.CharField(max_length=255, null=True)),
                ('profession', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('experience_tenure', models.CharField(choices=[('Fresher', 'Fresher'), ('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 year'), ('4 years', '4years'), ('5 years', '5 years')], default='Fresher', max_length=10)),
                ('experience_level', models.CharField(choices=[('Manager', 'Manager'), ('Student', 'Student'), ('Officer', 'Officer'), ('Executive', 'Executive')], default='Student', max_length=10)),
                ('qualification', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PHD', 'PHD')], default='Bachelor', max_length=10)),
                ('contract_type', models.CharField(choices=[('Manager', 'Manager'), ('Student', 'Student'), ('Officer', 'Officer'), ('Executive', 'Executive')], default='Internship', max_length=10)),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('salry_type', models.CharField(choices=[('Manager', 'Manager'), ('Student', 'Student'), ('Officer', 'Officer'), ('Executive', 'Executive')], default='Monthly', max_length=10)),
                ('salary_amount', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(choices=[('Manager', 'Manager'), ('Student', 'Student'), ('Officer', 'Officer'), ('Executive', 'Executive')], default='Rupees', max_length=10)),
                ('Marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=10)),
                ('set_your_profile', models.CharField(choices=[('0', 'Public'), ('1', 'Private')], default='Public', max_length=20)),
                ('about_yourself', models.CharField(max_length=2000, null=True)),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('company_specialization', models.CharField(choices=[('0', 'Php'), ('1', 'JS'), ('2', 'Designing'), ('3', 'Application development'), ('4', 'Painting'), ('5', 'Arts'), ('6', 'Development'), ('7', 'Modeling'), ('8', 'SEO'), ('9', 'Architecture'), ('10', 'Management'), ('11', 'SMM'), ('12', 'Culinary Arts'), ('13', 'Peruvian Cuisine'), ('14', 'Team Management'), ('15', 'patience'), ('16', 'Commitment'), ('17', 'Team Work'), ('18', 'Flexibility'), ('19', 'Stress Management'), ('20', 'Analytical skills'), ('21', 'trainings'), ('22', 'communication skills'), ('23', 'Food Products'), ('24', 'Education'), ('25', 'cooking')], default='Php', max_length=20)),
                ('location', models.CharField(max_length=255, null=True)),
                ('Facebook', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('edudetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
                ('employeeuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('jobexp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Jobexperience')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
    ]
