# Generated by Django 2.2.2 on 2020-07-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_employee_jobexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='edudetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Education'),
        ),
    ]
