# Generated by Django 2.2.2 on 2020-07-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200713_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='euser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
