# Generated by Django 2.2.2 on 2020-07-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200713_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='edudetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='jobexp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Jobexperience'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='projdetails',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
        ),
    ]
