# Generated by Django 2.2.2 on 2020-07-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200713_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobexperience',
            options={'verbose_name': 'applicant', 'verbose_name_plural': 'applicants'},
        ),
    ]
