# Generated by Django 2.2.2 on 2020-07-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200713_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='edudetails',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='jobexp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='projdetails',
        ),
    ]
