# Generated by Django 2.2.2 on 2020-07-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200713_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_emp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seek',
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_specialization',
            field=models.CharField(choices=[('Php', 'Php'), ('JS', 'JS'), ('Designing', 'Designing'), ('Application development', 'Application development'), ('Painting', 'Painting'), ('Arts', 'Arts'), ('Development', 'Development'), ('Modeling', 'Modeling'), ('SEO', 'SEO'), ('Architecture', 'Architecture'), ('Management', 'Management'), ('SMM', 'SMM'), ('Culinary Arts', 'Culinary Arts'), ('Peruvian Cuisine', 'Peruvian Cuisine'), ('Team Management', 'Team Management'), ('patience', 'patience'), ('Commitment', 'Commitment'), ('Team Work', 'Team Work'), ('Flexibility', 'Flexibility'), ('Stress Management', 'Stress Management'), ('Analytical skills', 'Analytical skills'), ('trainings', 'trainings'), ('communication skills', 'communication skills'), ('Food Products', 'Food Products'), ('Education', 'Education'), ('cooking', 'cooking')], default='Php', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='set_your_profile',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_specialization',
            field=models.CharField(choices=[('Php', 'Php'), ('JS', 'JS'), ('Designing', 'Designing'), ('Application development', 'Application development'), ('Painting', 'Painting'), ('Arts', 'Arts'), ('Development', 'Development'), ('Modeling', 'Modeling'), ('SEO', 'SEO'), ('Architecture', 'Architecture'), ('Management', 'Management'), ('SMM', 'SMM'), ('Culinary Arts', 'Culinary Arts'), ('Peruvian Cuisine', 'Peruvian Cuisine'), ('Team Management', 'Team Management'), ('patience', 'patience'), ('Commitment', 'Commitment'), ('Team Work', 'Team Work'), ('Flexibility', 'Flexibility'), ('Stress Management', 'Stress Management'), ('Analytical skills', 'Analytical skills'), ('trainings', 'trainings'), ('communication skills', 'communication skills'), ('Food Products', 'Food Products'), ('Education', 'Education'), ('cooking', 'cooking')], default='Php', max_length=20),
        ),
    ]
