# Generated by Django 2.2.2 on 2020-07-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200713_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpack',
            name='canid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='jobtenure1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mention Job Tenure For the above role'),
        ),
    ]
