# Generated by Django 2.2.2 on 2020-07-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200713_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpack',
            name='canid',
        ),
        migrations.AlterField(
            model_name='subscriptionpack',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
