# Generated by Django 2.2.2 on 2020-07-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200713_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Jobpost')),
            ],
            options={
                'verbose_name': 'savedjob',
                'verbose_name_plural': 'savedjobs',
            },
        ),
    ]
