# Generated by Django 2.2.2 on 2020-07-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200715_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='user',
            new_name='userr',
        ),
        migrations.AddField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_emp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_seek',
            field=models.BooleanField(default=False),
        ),
    ]
