# Generated by Django 2.2.2 on 2020-07-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200716_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='userr',
            new_name='user',
        ),
    ]
