# Generated by Django 2.2.2 on 2020-07-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200716_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settime',
            options={'verbose_name': 'settime'},
        ),
        migrations.AlterField(
            model_name='education',
            name='CGPA_For_masters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settime',
            name='intime',
            field=models.TimeField(verbose_name='Enter time in IST date time format(hh:mm:ss)'),
        ),
    ]
