# Generated by Django 2.2.2 on 2020-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20200716_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='set_your_profile',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20),
        ),
    ]
