# Generated by Django 2.2.2 on 2020-07-18 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200717_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='posted_on',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('expired', 'expired'), ('active', 'active')], default='expired', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='valid_till',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Enter date in yy-mm-dd format'),
        ),
    ]
