# Generated by Django 2.2.2 on 2020-07-19 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0038_auto_20200718_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionid', models.CharField(choices=[('499 per month', '499 per month'), ('Yearly subscription @3400', 'Yearly subscription @3400')], default='499 per month', max_length=20)),
                ('status', models.CharField(choices=[('expired', 'expired'), ('active', 'active')], default='expired', max_length=20)),
                ('price', models.IntegerField(choices=[(0, 'Monthly_499'), (1, 'Yearly_3400')], default=0)),
                ('purchasedate', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscription',
            },
        ),
        migrations.DeleteModel(
            name='subscriptionpack',
        ),
    ]
