# Generated by Django 2.2.2 on 2020-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200719_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriptionid',
            field=models.CharField(choices=[('499 per month', '499 per month'), ('Yearly subscription @3400', 'Yearly subscription @3400')], default='499 per month', max_length=40),
        ),
    ]
