# Generated by Django 2.2.2 on 2020-07-21 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20200719_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedresume',
            name='empid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer'),
        ),
    ]
