# Generated by Django 2.2.2 on 2020-07-21 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20200720_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedresume',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer'),
        ),
    ]
