# Generated by Django 2.2.2 on 2020-07-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20200720_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='prev_Employments',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your Previous employments'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your Skils'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='This is the name of Organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your hobbies'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prev_Employments',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your Previous employments'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(max_length=255, null=True, verbose_name='Mention Your Skils'),
        ),
    ]
