# Generated by Django 2.2.2 on 2020-07-23 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20200721_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='valid_till',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Enter last date of applying in yy-mm-dd format :'),
        ),
    ]
