# Generated by Django 2.2.2 on 2020-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20200723_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='contractType',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary'), ('Walk-In', 'Walk-In'), ('Fresher', 'Fresher')], default='Fresher', max_length=255, verbose_name='Contract type of this jobpost'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='hear',
            field=models.CharField(choices=[('Mail', 'Mail'), ('Tv', 'Tv'), ('Newspapaer', 'Newspapaer'), ('other', 'other')], default='Newspaper', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='jobType',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], default='Full time', max_length=255),
        ),
    ]
