# Generated by Django 2.2.2 on 2020-07-28 07:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20200727_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpostt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(max_length=250, null=True)),
                ('JobDesciption', models.CharField(max_length=255, null=True)),
                ('CompanyName', models.CharField(max_length=250, null=True)),
                ('Jobindustry', models.CharField(max_length=250, null=True)),
                ('posted_on', models.DateField(default=datetime.datetime.today)),
                ('requirements', models.CharField(max_length=255, null=True)),
                ('valid_till', models.DateField(default=datetime.datetime.today, verbose_name='Enter last date of applying in yy-mm-dd format :')),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('hear', models.CharField(max_length=255, null=True)),
                ('contractType', models.CharField(max_length=255, null=True)),
                ('jobType', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('no_of_employees', models.CharField(max_length=255, null=True)),
                ('updates_email', models.CharField(max_length=255, null=True)),
                ('salary_beg', models.CharField(max_length=255, null=True)),
                ('salary_end', models.CharField(max_length=255, null=True)),
                ('ad', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'Jobpostt',
                'verbose_name_plural': 'Jobpostts',
            },
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='status',
        ),
        migrations.AlterField(
            model_name='savedjobs',
            name='jid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Jobpostt'),
        ),
        migrations.CreateModel(
            name='applicantt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_emp', models.BooleanField(default=False)),
                ('is_seek', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.CharField(max_length=255, null=True, verbose_name='Mention Your Skils')),
                ('experience', models.CharField(max_length=255, null=True, verbose_name='experience')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('prev_Employments', models.CharField(max_length=255, null=True, verbose_name='Mention Your Previous employments')),
                ('education_details', models.CharField(max_length=255, null=True, verbose_name='Mention Your Education Details')),
                ('projects', models.CharField(max_length=255, null=True, verbose_name='Give a beief about your projects')),
                ('accomplishments', models.CharField(max_length=255, null=True, verbose_name='accomplishments')),
                ('otherLinks', models.URLField(blank=True, null=True)),
                ('job', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Jobpostt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'applicantt',
                'verbose_name_plural': 'applicantts',
            },
        ),
    ]
