# Generated by Django 2.2.2 on 2020-07-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20200727_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='set_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indate', models.DateField(verbose_name='Enter date in yyyy-mm-dd format')),
                ('intime', models.TimeField(verbose_name='Enter time in IST date time format(hh:mm:ss)')),
                ('apliid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicantt')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer')),
            ],
            options={
                'verbose_name': 'set_Time',
            },
        ),
    ]
