# Generated by Django 2.2.2 on 2020-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_svedresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostt',
            name='qualification',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
