# Generated by Django 2.2.2 on 2020-07-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_jobpostt_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostt',
            old_name='salary_beg',
            new_name='salary_currency',
        ),
        migrations.RenameField(
            model_name='jobpostt',
            old_name='salary_end',
            new_name='salary_type',
        ),
    ]
