# Generated by Django 2.2.2 on 2020-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20200729_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostt',
            name='job_experience',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpostt',
            name='job_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpostt',
            name='job_shift',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
